<a href="<?=$this->url('users/add')?>" class='btn btn-primary'>
    <?=$this->translate('__add_user')?>
</a>

<br/>
<br/>

<table class="table">
    <thead>
        <tr>
            <th>
                <a href="<?=$this->url('users/sort', array('field' => 'u.id'))?>" class="btn btn-xs"><i class="glyphicon glyphicon-chevron-down"></i></a>
                <?=$this->translate('__user_id')?>
            </th>
            <th>
                <a href="<?=$this->url('users/sort', array('field' => 'p.firstName'))?>" class="btn btn-xs"><i class="glyphicon glyphicon-chevron-down"></i></a>
                <?=$this->translate('__user_firstname')?>
            </th>
            <th>
                <a href="<?=$this->url('users/sort', array('field' => 'p.lastName'))?>" class="btn btn-xs"><i class="glyphicon glyphicon-chevron-down"></i></a>
                <?=$this->translate('__user_lastname')?>
            </th>
            <th>
                <a href="<?=$this->url('users/sort', array('field' => 'p.birthdate'))?>" class="btn btn-xs"><i class="glyphicon glyphicon-chevron-down"></i></a>
                <?=$this->translate('__user_birthdate')?>
            </th>
            <th>
                <a href="<?=$this->url('users/sort', array('field' => 'p.address'))?>" class="btn btn-xs"><i class="glyphicon glyphicon-chevron-down"></i></a>
                <?=$this->translate('__user_address')?>
            </th>
            <th>
                <a href="<?=$this->url('users/sort', array('field' => 'u.email'))?>" class="btn btn-xs"><i class="glyphicon glyphicon-chevron-down"></i></a>
                <?=$this->translate('__user_email')?>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php
    /* @var $user \Application\Entity\User */
    foreach($this->users as $user)
    {
        ?>
        <tr>
        <td>
            <?=$user['id']?>
        </td>
        <td>
            <?=$user['profile']['firstname']?>
        </td>
        <td>
            <?=$user['profile']['lastname']?>
        </td>
        <td>
            <?=$user['profile']['birthdate']?>
        </td>
        <td>
            <?=$user['profile']['address']?>
        </td>
        <td>
            <a href='mailto:<?=$user['email']?>'>
                <?=$user['email']?>
            </a>
        </td>
        <td>
            <a href="<?=$this->url('users/edit', array('user_id'   =>  $user['id']))?>" class="btn btn-success">
                <?=$this->translate('__edit_user')?>
            </a>
           <a href="<?=$this->url('users/remove', array('user_id'   =>  $user['id']))?>" class="btn btn-danger">
            <?=$this->translate('__remove_user')?>
           </a>
        </td>
        </tr>
        <?php
    }
    ?>
    </tbody>
</table>